pub mod computer;
pub mod day01;
#[cfg(feature = "visualization")]
pub mod day01_renderer;
pub mod day02;
pub mod day03;
#[cfg(feature = "visualization")]
pub mod day03_renderer;
pub mod day04;
pub mod day05;
pub mod day06;
pub mod day07;
pub mod day08;
#[cfg(feature = "visualization")]
pub mod day08_renderer;
pub mod day09;
#[cfg(feature = "visualization")]
pub mod day09_renderer;
pub mod day10;
