pub mod day01;
#[cfg(feature = "visualization")]
pub mod day01_renderer;
pub mod day02;
pub mod day03;
#[cfg(feature = "visualization")]
pub mod day03_renderer;
pub mod day04;
pub mod day05;
pub mod day06;
pub mod day07;
pub mod day08;
#[cfg(feature = "visualization")]
pub mod day08_renderer;
pub mod day09;
pub mod day10;
pub mod day11;
#[cfg(feature = "visualization")]
pub mod day11_renderer;
pub mod day12;
#[cfg(feature = "visualization")]
pub mod day12_renderer;
pub mod day13;
pub mod day14;
pub mod day15;
pub mod day16;
pub mod day17;
pub mod day18;
pub mod day19;
pub mod day20;
pub mod day21;
pub mod day22;
pub mod day23;
pub mod day24;
pub mod day25;
