[package]
name = "advent-of-code-fuzzing-libfuzzer-placeholder"
version = "1.0.0"
keywords = ["advent-of-code", "rust", "libfuzzer", "fuzzing"]
categories = ["algorithms", "rust-patterns"]
authors = ["Fredrik Fornwall <fredrik@fornwall.net>"]
repository = "https://github.com/fornwall/advent-of-code"
description = "Fuzzing of solutions to Advent of Code written in Rust"
license = "MIT"
edition = "2021"
