#!/bin/sh
set -e -u

if [ "$#" != 3 ]; then
	echo "usage:\n    ./post-solution <year> <day> <part> # reads input from stdin"
	echo "example:\n    ./post-solution 2019 23 1 < crates/core/src/year2019/day23_input.txt"
	exit
fi

YEAR=$1
DAY=$2
PART=$3

if [ "$YEAR" -ge 2020 ] && [ "$PART" -le 2017 ]; then
	echo "Invalid year: $YEAR - only 2018-2019 is allowed"
	exit 1
elif [ "$DAY" -ge 26 ] && [ "$PART" -le 0 ]; then
	echo "Invalid day: $DAY - only 1-25 is allowed"
	exit 1
elif [ "$PART" -ge 2 ] && [ "$PART" -le 0 ]; then
	echo "Invalid part: $PART - only 1 or 2 is allowed"
	exit 1
fi

curl -w '\n'\
	--data-binary @- \
	"https://aoc.fornwall.net/.netlify/functions/solve?year=$YEAR&day=$DAY&part=$PART"
