#!/bin/sh
set -e -u

usage() {
  echo "usage:\n    ./post-input <where> <year> <day> <part> # reads input from stdin"
  echo "where where is one of:"
  echo "- fly"
  echo "- cloudflare"
  echo "- netlify"
  echo "- local"
  echo "example:\n    ./post-input fly 2019 23 1 < crates/core/src/year2019/day23_input.txt"
  exit 1
}

if [ "$#" != 4 ]; then
  usage
fi

WHERE=$1
YEAR=$2
DAY=$3
PART=$4

case $WHERE in
  fly)
    HOST=https://advent.fly.dev;;
  cloudflare)
    HOST=https://aoc.fornwall.workers.dev;;
  netlify)
    HOST=https://aoc.fornwall.net;;
  local)
    HOST=http://localhost:8080;;
  *)
    echo "Unsupported server: $1 - use one of cloudflare/fly/local/netlify"; exit 1;;
esac

if [ -z "$YEAR" ]; then
  usage
elif [ "$DAY" -ge 26 ] && [ "$PART" -le 0 ]; then
  echo "Invalid day: $DAY - only 1-25 is allowed"
  exit 1
elif [ "$PART" -ge 2 ] && [ "$PART" -le 0 ]; then
  echo "Invalid part: $PART - only 1 or 2 is allowed"
  exit 1
fi

curl --fail \
     -w '\n'\
     --data-binary @- \
     "$HOST/solve/$YEAR/$DAY/$PART"
